name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements-dev.txt
      - run: isort --check-only .
      - run: black --check .

  test-python:
    runs-on: ubuntu-latest
    needs: lint-python
    env:
      # Expose the HMAC creds and bucket names to your tests
      GCS_HMAC_KEY_ID:       ${{ secrets.GCS_HMAC_KEY_ID }}
      GCS_HMAC_SECRET:       ${{ secrets.GCS_HMAC_SECRET }}
      DUCKLAKE_BUCKET:       ${{ secrets.DUCKLAKE_BUCKET_NAME }}
      RAW_BUCKET:            ${{ secrets.RAW_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: python -m pytest -q

  test-sqlmesh:
    runs-on: ubuntu-latest
    env:
      GCS_HMAC_KEY_ID:       ${{ secrets.GCS_HMAC_KEY_ID }}
      GCS_HMAC_SECRET:       ${{ secrets.GCS_HMAC_SECRET }}
      DUCKLAKE_BUCKET:       ${{ secrets.DUCKLAKE_BUCKET }}
      RAW_BUCKET:            ${{ secrets.RAW_BUCKET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install sqlmesh duckdb
      - name: Run SQLMesh tests
        working-directory: Sqlmesh
        run: sqlmesh test

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test-python
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
      - name: Build & push Docker image
        run: |
          IMAGE_URI=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REPO_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          echo "Built image: $IMAGE_URI"
          docker buildx build --platform linux/amd64 -t $IMAGE_URI --push .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

  terraform-plan:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Decode SA key
        run: |
          echo "$GCP_SA_KEY_B64" | base64 --decode > "${HOME}/gcp-sa-key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcp-sa-key.json"
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.12.2'
          
      - name: Terraform fmt & init
        working-directory: Terraform
        env:
          TF_VAR_project_id:            ${{ secrets.GCP_PROJECT }}
          TF_VAR_region:                ${{ secrets.GCP_REGION }}
          TF_VAR_raw_bucket_name:       ${{ secrets.RAW_BUCKET }}
          TF_VAR_ducklake_bucket_name:  ${{ secrets.DUCKLAKE_BUCKET }}
          TF_VAR_artifact_repo_id:      ${{ secrets.ARTIFACT_REPO_ID }}
          TF_VAR_image_uri:             ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REPO_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          TF_VAR_cloud_run_service:     ${{ secrets.CLOUD_RUN_SERVICE }}
          ACTIONS_RUNTIME_TOKEN:        ${{secrets.ACTIONS_RUNTIME_TOKEN}}
          ACTIONS_RUNTIME_URL:          ${{secrets.ACTIONS_RUNTIME_URL}}
          TF_STATE_BUCKET:              ${{secrets.TF_STATE_BUCKET}}
        run: |
          terraform fmt -check -recursive
          terraform init \
            -input=false \
            -reconfigure \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="prefix=clinical-trials/terraform/state"
      - name: Terraform validate & plan
        working-directory: Terraform
        env:
          TF_VAR_project_id:            ${{ secrets.GCP_PROJECT }}
          TF_VAR_region:                ${{ secrets.GCP_REGION }}
          TF_VAR_raw_bucket_name:       ${{ secrets.RAW_BUCKET }}
          TF_VAR_ducklake_bucket_name:  ${{ secrets.DUCKLAKE_BUCKET }}
          TF_VAR_artifact_repo_id:      ${{ secrets.ARTIFACT_REPO_ID }}
          TF_VAR_image_uri:             ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REPO_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          TF_VAR_cloud_run_service:     ${{ secrets.CLOUD_RUN_SERVICE }}
        run: |
          terraform validate -no-color
          terraform plan -out=tfplan -no-color

      - name: Terraform apply
        working-directory: Terraform
        env:
          TF_VAR_project_id:            ${{ secrets.GCP_PROJECT }}
          TF_VAR_region:                ${{ secrets.GCP_REGION }}
          TF_VAR_raw_bucket_name:       ${{ secrets.RAW_BUCKET }}
          TF_VAR_ducklake_bucket_name:  ${{ secrets.DUCKLAKE_BUCKET }}
          TF_VAR_artifact_repo_id:      ${{ secrets.ARTIFACT_REPO_ID }}
          TF_VAR_image_uri:             ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REPO_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          TF_VAR_cloud_run_service:     ${{ secrets.CLOUD_RUN_SERVICE }}
        run: |
          
          terraform apply -auto-approve
      

  
  